name: authentication_repository
description: "Dart package which manahes authentication"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.4"
  flutter: ">=1.17.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth_platform_interface: ^7.4.10
  firebase_core_platform_interface: ^5.4.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
