from fastapi import FastAPI


from app.firestore import Firestore
from app.ai import ChatEngine

app = FastAPI()

@app.post('/chat/{chat_id}')
def get_response(chat_id: str):
    '''Sending a response generated by chatbot'''
    firestore = Firestore(chat_id=chat_id)
    
    last_messages = firestore.last_n_messages(20)
    last_messages = [('Bot: ' if message['author_id'] == 'bot_id' else 'User: ' ) + "\'" + message['text'] + "\'" for message in last_messages]
    summary = firestore.get_summary()
    messages_count = firestore.messages_count()
    print(last_messages)

    if messages_count % 20 == 0:
        new_summary = ChatEngine().summarize(new_messages=last_messages, prev_summary=summary)
        firestore.update_summary(str(new_summary.text))

    response = ChatEngine().generate_response(
        query=last_messages[0],
        summary=summary,
        last_messages=last_messages
    )

    firestore.send_message(str(response))

@app.delete('/chat/{chat_id}/delete_history')
def delete_history(chat_id: str):
    firestore = Firestore(chat_id=chat_id)
    firestore.delete_collection(firestore.messages, firestore.messages_count())
    firestore.update_messages_count(0)
